// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikirrrvvyqsvznrzmvwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlraXJycnZ2eXFzdnpucnptdnd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDYyMTgsImV4cCI6MjA3Mzg4MjIxOH0.rVGrsuvpJ18fCjQ64Q6ns1_fEhh3MhAEGAPBYPTgclI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});